# Generated by Django 6.0.1 on 2026-01-13 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdminMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(limit_choices_to={'is_staff': True, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': False, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_mapping', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
